### ISSUE TITLE
Generation of files in "examples/direct/expected"

### ISSUE THREAD

**Issue by carpetaa** [hughperkins/VeriGPU#12]
Hi, I am adding some more direct test ASMs to the project so xxxx_expected.txt should also be added.

I'd like to know, how the files in "examples/direct/expected" are generated? I didn't see any info about this in docs.

**Comment by hughperkins** [comment]
Ran the code, checked the output matched my expectations, copy/pasted into the expected output.

The idea being that I only have to manually check the output once, and then any deviations from that will cause a test failure.

**Comment by carpetaa** [comment]
Yeah, sounds reasonable, and thanks.
