### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by bekbeis** [hughperkins/VeriGPU#15]
Hi,

Do you guys have any reports related to coverage of your verification infrastructure? In other words, how good/mature is your verification environment?

Thanks!

**Comment by hughperkins** [comment]
Verification is described at https://github.com/hughperkins/VeriGPU/blob/main/docs/verification.md . There aren't any coverage reports. Is adding coverage reports something you could be interested in helping with?

**Comment by bekbeis** [comment]
Maybe sometime in the future. Thank you a lot for your fast response!
