### ISSUE TITLE
Any specific environment?

### ISSUE THREAD

**Issue by redpanda3** [hughperkins/VeriGPU#9]
Hi, I got some error message during make gpu runtime. 
```
error: ‘class llvm::ElementCount’ has no member named ‘getFixedValue’
         int elementCount = vectorType->getElementCount().getFixedValue();
```

The environment is ubuntu20 with clang 10.

**Comment by hughperkins** [comment]
There's a dockerfile at https://github.com/hughperkins/VeriGPU/blob/main/cicd/Dockerfile This should tell you an exact recipe I think? (If you haven't used dockerfiles before:
- `FROM` tells you which os and version
- `RUN` are bash commands

You need clang14 https://github.com/hughperkins/VeriGPU/blob/501caddd100e5245658008bb42f17ef8e97d4192/cicd/Dockerfile#L39-L44

**Comment by redpanda3** [comment]
Thank you, issue solved. My llvm version is still on the 11th.
